
[2025-02-06 11:11:13] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:14] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:15] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:15] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:15] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/callee16/test_repo/

[2025-02-06 11:11:16] INFO - handler.py: 77

Container xuehang_16_pillow_3.11__Thu__Feb____6__11_10_33__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-06 11:11:16] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/callee16/test_repo/`

[2025-02-06 11:11:16] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `is_big_endian` in the context_code.

[2025-02-06 11:11:16] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/callee16/test_repo/Tests/helper.py' already exists.

[2025-02-06 11:11:16] INFO - callee_builder.py: 305

Using docker image with ID: fc29e8ee0f09

[2025-02-06 11:11:16] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee16/test_repo/`.

Skipping repo clone...

[2025-02-06 11:11:16] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `is_big_endian` in the context_code.

[2025-02-06 11:11:16] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/callee16/test_repo/Tests/helper.py

[2025-02-06 11:11:16] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/callee16/test_repo/Tests/helper.py'

[2025-02-06 11:11:16] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/Tests/test_imagefile.py` in Docker container `xuehang_16_pillow_container__is_big_endian__Thu_Feb__6_11_11_16_2025`...

[2025-02-06 11:11:16] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:16] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:17] INFO - callee_builder.py: 297

Preparing docker env for execution test...

[2025-02-06 11:11:17] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack'
Attempting directory removal again...

[2025-02-06 11:11:17] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects'
Attempting directory removal again...

[2025-02-06 11:11:17] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 340)

[2025-02-06 11:11:17] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git'
Attempting directory removal again...

[2025-02-06 11:11:17] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest'
Attempting directory removal again...

[2025-02-06 11:11:17] INFO - callee_builder.py: 134

Successfully removed directory at '/shared/nas2/xuehangg/syncbench_build/code/callee7/'

[2025-02-06 11:11:17] INFO - builder.py: 176

Checking if Docker image 'xuehang/7_pytest' exists...

Docker image 'xuehang/7_pytest' already exists with ID: 2ad0b81aebdc

[2025-02-06 11:11:17] INFO - handler.py: 30

Successfiully created local path: `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-06 11:11:17] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 340)

[2025-02-06 11:11:18] INFO - handler.py: 42

Container xuehang_7_pytest_3.11__Thu__Feb____6__11_11_17__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-06 11:11:18] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 372)

[2025-02-06 11:11:18] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/

[2025-02-06 11:11:18] INFO - handler.py: 77

Container xuehang_21_mlflow_3.11__Thu__Feb____6__11_10_20__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-06 11:11:18] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/`

[2025-02-06 11:11:19] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `test_get_class_from_string` in the context_code.

[2025-02-06 11:11:19] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/tests/utils/test_class_utils.py' already exists.

[2025-02-06 11:11:19] INFO - caller_builder.py: 310

Using docker image with ID: 73f308f5c08c

[2025-02-06 11:11:19] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/`.

Skipping repo clone...

[2025-02-06 11:11:19] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `test_get_class_from_string` in the context_code.

[2025-02-06 11:11:19] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/tests/utils/test_class_utils.py

[2025-02-06 11:11:19] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/tests/utils/test_class_utils.py'

[2025-02-06 11:11:19] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/tests/utils/test_class_utils.py` in Docker container `xuehang_21_mlflow_container__test_get_class_from_string__Thu_Feb__6_11_11_19_2025`...

[2025-02-06 11:11:19] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 373)

[2025-02-06 11:11:19] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 369)

[2025-02-06 11:11:19] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 368)

[2025-02-06 11:11:20] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 367)

[2025-02-06 11:11:20] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/

[2025-02-06 11:11:20] INFO - handler.py: 77

Container xuehang_7_pytest_3.11__Thu__Feb____6__11_11_17__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-06 11:11:20] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-06 11:11:20] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `cleanup_on_exit` in the context_code.

[2025-02-06 11:11:20] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py' already exists.

[2025-02-06 11:11:20] INFO - callee_builder.py: 305

Using docker image with ID: 2ad0b81aebdc

[2025-02-06 11:11:20] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`.

Skipping repo clone...

[2025-02-06 11:11:20] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `cleanup_on_exit` in the context_code.

[2025-02-06 11:11:20] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 362)

[2025-02-06 11:11:20] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py

[2025-02-06 11:11:20] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py'

[2025-02-06 11:11:20] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/testing/test_pathlib.py` in Docker container `xuehang_7_pytest_container_cleanup_on_exit_Thu_Feb__6_11_11_20_2025`...

[2025-02-06 11:11:20] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:21] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 356)

[2025-02-06 11:11:21] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 326)

[2025-02-06 11:11:22] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:22] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:23] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:24] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:24] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/

[2025-02-06 11:11:24] INFO - handler.py: 77

Container xuehang_21_mlflow_3.11__Thu__Feb____6__11_10_30__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-06 11:11:24] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/`

[2025-02-06 11:11:24] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `_restore_experiment` in the context_code.

[2025-02-06 11:11:25] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:25] INFO - tester.py: 92

Execution succeeded!
Container output: 
Obtaining file:///workspace/test_repo
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: Flask<4 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (3.0.3)
Requirement already satisfied: Jinja2<4,>=2.11 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (3.1.4)
Requirement already satisfied: alembic!=1.10.0,<2 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (1.13.2)
Requirement already satisfied: cachetools<6,>=5.0.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (8.1.7)
Requirement already satisfied: cloudpickle<4 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (3.0.0)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (0.32.0)
Requirement already satisfied: docker<8,>=4.0.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (7.1.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (3.1.43)
Requirement already satisfied: graphene<4 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (3.3)
Requirement already satisfied: gunicorn<24 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (23.0.0)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (8.4.0)
Requirement already satisfied: markdown<4,>=3.3 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (3.7)
Requirement already satisfied: matplotlib<4 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (3.9.2)
Requirement already satisfied: numpy<3 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (2.1.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (1.27.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (1.27.0)
Requirement already satisfied: packaging<25 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (24.1)
Requirement already satisfied: pandas<3 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (2.2.2)
Requirement already satisfied: protobuf<6,>=3.12.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (5.28.0)
Requirement already satisfied: pyarrow<18,>=4.0.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (17.0.0)
Requirement already satisfied: pyyaml<7,>=5.1 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (2.32.3)
Requirement already satisfied: scikit-learn<2 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (1.5.1)
Requirement already satisfied: scipy<2 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (1.14.1)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (2.0.34)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /workspace/test_venv/lib/python3.11/site-packages (from mlflow==2.16.1.dev0) (0.5.1)
Requirement already satisfied: Mako in /workspace/test_venv/lib/python3.11/site-packages (from alembic!=1.10.0,<2->mlflow==2.16.1.dev0) (1.3.5)
Requirement already satisfied: typing-extensions>=4 in /workspace/test_venv/lib/python3.11/site-packages (from alembic!=1.10.0,<2->mlflow==2.16.1.dev0) (4.12.2)
Requirement already satisfied: google-auth~=2.0 in /workspace/test_venv/lib/python3.11/site-packages (from databricks-sdk<1,>=0.20.0->mlflow==2.16.1.dev0) (2.34.0)
Requirement already satisfied: urllib3>=1.26.0 in /workspace/test_venv/lib/python3.11/site-packages (from docker<8,>=4.0.0->mlflow==2.16.1.dev0) (2.2.2)
Requirement already satisfied: Werkzeug>=3.0.0 in /workspace/test_venv/lib/python3.11/site-packages (from Flask<4->mlflow==2.16.1.dev0) (3.0.4)
Requirement already satisfied: itsdangerous>=2.1.2 in /workspace/test_venv/lib/python3.11/site-packages (from Flask<4->mlflow==2.16.1.dev0) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in /workspace/test_venv/lib/python3.11/site-packages (from Flask<4->mlflow==2.16.1.dev0) (1.8.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /workspace/test_venv/lib/python3.11/site-packages (from gitpython<4,>=3.1.9->mlflow==2.16.1.dev0) (4.0.11)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /workspace/test_venv/lib/python3.11/site-packages (from graphene<4->mlflow==2.16.1.dev0) (3.2.4)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /workspace/test_venv/lib/python3.11/site-packages (from graphene<4->mlflow==2.16.1.dev0) (3.2.0)
Requirement already satisfied: aniso8601<10,>=8 in /workspace/test_venv/lib/python3.11/site-packages (from graphene<4->mlflow==2.16.1.dev0) (9.0.1)
Requirement already satisfied: zipp>=0.5 in /workspace/test_venv/lib/python3.11/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow==2.16.1.dev0) (3.20.1)
Requirement already satisfied: MarkupSafe>=2.0 in /workspace/test_venv/lib/python3.11/site-packages (from Jinja2<4,>=2.11->mlflow==2.16.1.dev0) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in /workspace/test_venv/lib/python3.11/site-packages (from matplotlib<4->mlflow==2.16.1.dev0) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /workspace/test_venv/lib/python3.11/site-packages (from matplotlib<4->mlflow==2.16.1.dev0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /workspace/test_venv/lib/python3.11/site-packages (from matplotlib<4->mlflow==2.16.1.dev0) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /workspace/test_venv/lib/python3.11/site-packages (from matplotlib<4->mlflow==2.16.1.dev0) (1.4.7)
Requirement already satisfied: pillow>=8 in /workspace/test_venv/lib/python3.11/site-packages (from matplotlib<4->mlflow==2.16.1.dev0) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /workspace/test_venv/lib/python3.11/site-packages (from matplotlib<4->mlflow==2.16.1.dev0) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /workspace/test_venv/lib/python3.11/site-packages (from matplotlib<4->mlflow==2.16.1.dev0) (2.9.0.post0)
Requirement already satisfied: deprecated>=1.2.6 in /workspace/test_venv/lib/python3.11/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow==2.16.1.dev0) (1.2.14)
Requirement already satisfied: opentelemetry-semantic-conventions==0.48b0 in /workspace/test_venv/lib/python3.11/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow==2.16.1.dev0) (0.48b0)
Requirement already satisfied: pytz>=2020.1 in /workspace/test_venv/lib/python3.11/site-packages (from pandas<3->mlflow==2.16.1.dev0) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /workspace/test_venv/lib/python3.11/site-packages (from pandas<3->mlflow==2.16.1.dev0) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /workspace/test_venv/lib/python3.11/site-packages (from requests<3,>=2.17.3->mlflow==2.16.1.dev0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /workspace/test_venv/lib/python3.11/site-packages (from requests<3,>=2.17.3->mlflow==2.16.1.dev0) (3.8)
Requirement already satisfied: certifi>=2017.4.17 in /workspace/test_venv/lib/python3.11/site-packages (from requests<3,>=2.17.3->mlflow==2.16.1.dev0) (2024.8.30)
Requirement already satisfied: joblib>=1.2.0 in /workspace/test_venv/lib/python3.11/site-packages (from scikit-learn<2->mlflow==2.16.1.dev0) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /workspace/test_venv/lib/python3.11/site-packages (from scikit-learn<2->mlflow==2.16.1.dev0) (3.5.0)
Requirement already satisfied: greenlet!=0.4.17 in /workspace/test_venv/lib/python3.11/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.16.1.dev0) (3.0.3)
Requirement already satisfied: wrapt<2,>=1.10 in /workspace/test_venv/lib/python3.11/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow==2.16.1.dev0) (1.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /workspace/test_venv/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow==2.16.1.dev0) (5.0.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /workspace/test_venv/lib/python3.11/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow==2.16.1.dev0) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /workspace/test_venv/lib/python3.11/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow==2.16.1.dev0) (4.9)
Requirement already satisfied: six>=1.5 in /workspace/test_venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib<4->mlflow==2.16.1.dev0) (1.16.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /workspace/test_venv/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow==2.16.1.dev0) (0.6.0)
Building wheels for collected packages: mlflow
  Building editable for mlflow (pyproject.toml): started
  Building editable for mlflow (pyproject.toml): finished with status 'done'
  Created wheel for mlflow: filename=mlflow-2.16.1.dev0-0.editable-py3-none-any.whl size=19576 sha256=333fc7ef8acd7bcc6cf261c4e6ed85db8840dee6236a1f0d347976bc8d116ebe
  Stored in directory: /tmp/pip-ephem-wheel-cache-933q2qpx/wheels/77/6d/8d/6d288ec591919a528b58517c67f4d12e0e98d23d266200ee38
Successfully built mlflow
Installing collected packages: mlflow
  Attempting uninstall: mlflow
    Found existing installation: mlflow 2.16.1.dev0
    Not uninstalling mlflow at /workspace/test_repo, outside environment /workspace/test_venv
    Can't uninstall 'mlflow'. No files were found to uninstall.
Successfully installed mlflow-2.16.1.dev0
[1m============================= test session starts ==============================[0m
platform linux -- Python 3.11.9, pytest-8.3.2, pluggy-1.5.0 -- /workspace/test_venv/bin/python
cachedir: .pytest_cache
rootdir: /workspace/test_repo
configfile: pytest.ini
plugins: asyncio-0.24.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
[1mcollecting ... [0mcollected 1 item

tests/utils/test_class_utils.py::test_get_class_from_string [32mPASSED[0m[33m       [100%][0m

[33m=============================== warnings summary ===============================[0m
../test_venv/lib/python3.11/site-packages/_pytest/config/__init__.py:1437
  /workspace/test_venv/lib/python3.11/site-packages/_pytest/config/__init__.py:1437: PytestConfigWarning: Unknown config option: timeout
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================= slowest 10 durations =============================
0.00s setup    tests/utils/test_class_utils.py::test_get_class_from_string
0.00s teardown tests/utils/test_class_utils.py::test_get_class_from_string
0.00s call     tests/utils/test_class_utils.py::test_get_class_from_string
[33m========================= [32m1 passed[0m, [33m[1m1 warning[0m[33m in 0.03s[0m[33m =========================[0m


[2025-02-06 11:11:25] INFO - tester.py: 168

[2025-02-06 11:11:25] INFO - tester.py: 180

[2025-02-06 11:11:25] INFO - tester.py: 257

{'total': 2, 'passed': 1, 'xpassed': 0, 'failed': 0, 'xfailed': 0, 'deselected': 0, 'skipped': 0, 'warning': 1, 'error': 0}

[2025-02-06 11:11:25] INFO - tester.py: 436

Number of test evals in current unit test: 2

[2025-02-06 11:11:25] INFO - tester.py: 66

Stopping and removing container 'xuehang_21_mlflow_container__test_get_class_from_string__Thu_Feb__6_11_11_19_2025'...

Successfully removed container 'xuehang_21_mlflow_container__test_get_class_from_string__Thu_Feb__6_11_11_19_2025'

[2025-02-06 11:11:25] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:25] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/mlflow/server/handlers.py' already exists.

[2025-02-06 11:11:25] INFO - callee_builder.py: 305

Using docker image with ID: 73f308f5c08c

[2025-02-06 11:11:25] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/`.

Skipping repo clone...

[2025-02-06 11:11:25] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `_restore_experiment` in the context_code.

[2025-02-06 11:11:26] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:26] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/mlflow/server/handlers.py

[2025-02-06 11:11:26] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/mlflow/server/handlers.py'

[2025-02-06 11:11:26] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/tests/tracking/test_rest_tracking.py` in Docker container `xuehang_21_mlflow_container___restore_experiment__Thu_Feb__6_11_11_26_2025`...

[2025-02-06 11:11:26] INFO - tester.py: 92

Execution succeeded!
Container output: 
Obtaining file:///workspace/test_repo
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: iniconfig in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (2.0.0)
Requirement already satisfied: packaging in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (24.1)
Requirement already satisfied: pluggy<2,>=1.5 in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (1.5.0)
Building wheels for collected packages: pytest
  Building editable for pytest (pyproject.toml): started
  Building editable for pytest (pyproject.toml): finished with status 'done'
  Created wheel for pytest: filename=pytest-8.4.0.dev64+g72c682ff9.d20250206-0.editable-py3-none-any.whl size=9450 sha256=1569605bc9dc40909acae9a4b6269bbb31dcbeb1d98e804ecf427379ee7bf4fb
  Stored in directory: /tmp/pip-ephem-wheel-cache-rkqw7397/wheels/77/6d/8d/6d288ec591919a528b58517c67f4d12e0e98d23d266200ee38
Successfully built pytest
Installing collected packages: pytest
  Attempting uninstall: pytest
    Found existing installation: pytest 8.4.0.dev64+g72c682ff9
    Uninstalling pytest-8.4.0.dev64+g72c682ff9:
      Successfully uninstalled pytest-8.4.0.dev64+g72c682ff9
Successfully installed pytest-8.4.0.dev64+g72c682ff9.d20250206
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.4.0.dev64+g72c682ff9.d20250206, pluggy-1.5.0 -- /workspace/test_venv/bin/python
cachedir: .pytest_cache
rootdir: /workspace/test_repo
configfile: pyproject.toml
plugins: asyncio-0.24.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
collecting ... collected 97 items

testing/test_pathlib.py::TestFNMatcherPort::test_matching[*.py-foo.py] PASSED [  1%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[*.py-bar/foo.py] PASSED [  2%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[test_*.py-foo/test_foo.py] PASSED [  3%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/*.py-tests/foo.py] PASSED [  4%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[/c/*.py-/c/foo.py] PASSED [  5%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[/c/foo/*.py-/c/foo/foo.py] PASSED [  6%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/test*.py-tests/foo/test_foo.py] PASSED [  7%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/doc/test*.py-tests/foo/bar/doc/test_foo.py] PASSED [  8%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/doc/**/test*.py-tests/foo/doc/bar/test_foo.py] PASSED [  9%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching_abspath PASSED [ 10%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[*.py-foo.pyc] PASSED [ 11%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[*.py-foo/foo.pyc] PASSED [ 12%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/*.py-foo/foo.py] PASSED [ 13%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[/c/*.py-/d/foo.py] PASSED [ 14%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[/c/foo/*.py-/d/foo/foo.py] PASSED [ 15%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/test*.py-tests/foo.py] PASSED [ 16%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/test*.py-foo/test_foo.py] PASSED [ 17%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/doc/test*.py-tests/foo/bar/doc/foo.py] PASSED [ 18%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/doc/test*.py-tests/foo/bar/test_foo.py] PASSED [ 19%]
testing/test_pathlib.py::TestImportPath::test_smoke_test[True] PASSED    [ 20%]
testing/test_pathlib.py::TestImportPath::test_smoke_test[False] PASSED   [ 21%]
testing/test_pathlib.py::TestImportPath::test_import_path_missing_file[True] PASSED [ 22%]
testing/test_pathlib.py::TestImportPath::test_import_path_missing_file[False] PASSED [ 23%]
testing/test_pathlib.py::TestImportPath::test_renamed_dir_creates_mismatch[True] PASSED [ 24%]
testing/test_pathlib.py::TestImportPath::test_renamed_dir_creates_mismatch[False] PASSED [ 25%]
testing/test_pathlib.py::TestImportPath::test_messy_name[True] PASSED    [ 26%]
testing/test_pathlib.py::TestImportPath::test_messy_name[False] PASSED   [ 27%]
testing/test_pathlib.py::TestImportPath::test_dir[True] PASSED           [ 28%]
testing/test_pathlib.py::TestImportPath::test_dir[False] PASSED          [ 29%]
testing/test_pathlib.py::TestImportPath::test_a[True] PASSED             [ 30%]
testing/test_pathlib.py::TestImportPath::test_a[False] PASSED            [ 31%]
testing/test_pathlib.py::TestImportPath::test_b[True] PASSED             [ 32%]
testing/test_pathlib.py::TestImportPath::test_b[False] PASSED            [ 34%]
testing/test_pathlib.py::TestImportPath::test_c[True] PASSED             [ 35%]
testing/test_pathlib.py::TestImportPath::test_c[False] PASSED            [ 36%]
testing/test_pathlib.py::TestImportPath::test_d[True] PASSED             [ 37%]
testing/test_pathlib.py::TestImportPath::test_d[False] PASSED            [ 38%]
testing/test_pathlib.py::TestImportPath::test_import_after[True] PASSED  [ 39%]
testing/test_pathlib.py::TestImportPath::test_import_after[False] PASSED [ 40%]
testing/test_pathlib.py::TestImportPath::test_check_filepath_consistency[True] PASSED [ 41%]
testing/test_pathlib.py::TestImportPath::test_check_filepath_consistency[False] PASSED [ 42%]
testing/test_pathlib.py::TestImportPath::test_ensuresyspath_append[True] PASSED [ 43%]
testing/test_pathlib.py::TestImportPath::test_ensuresyspath_append[False] PASSED [ 44%]
testing/test_pathlib.py::TestImportPath::test_invalid_path[True] PASSED  [ 45%]
testing/test_pathlib.py::TestImportPath::test_invalid_path[False] PASSED [ 46%]
testing/test_pathlib.py::TestImportPath::test_importmode_importlib[True] PASSED [ 47%]
testing/test_pathlib.py::TestImportPath::test_importmode_importlib[False] PASSED [ 48%]
testing/test_pathlib.py::TestImportPath::test_remembers_previous_imports[True] PASSED [ 49%]
testing/test_pathlib.py::TestImportPath::test_remembers_previous_imports[False] PASSED [ 50%]
testing/test_pathlib.py::TestImportPath::test_no_meta_path_found[True] PASSED [ 51%]
testing/test_pathlib.py::TestImportPath::test_no_meta_path_found[False] PASSED [ 52%]
testing/test_pathlib.py::test_resolve_package_path PASSED                [ 53%]
testing/test_pathlib.py::test_package_unimportable PASSED                [ 54%]
testing/test_pathlib.py::test_access_denied_during_cleanup PASSED        [ 55%]
testing/test_pathlib.py::test_long_path_during_cleanup PASSED            [ 56%]
testing/test_pathlib.py::test_get_extended_length_path_str PASSED        [ 57%]
testing/test_pathlib.py::test_suppress_error_removing_lock PASSED        [ 58%]
testing/test_pathlib.py::test_bestrelpath PASSED                         [ 59%]
testing/test_pathlib.py::test_commonpath PASSED                          [ 60%]
testing/test_pathlib.py::test_visit_ignores_errors PASSED                [ 61%]
testing/test_pathlib.py::test_samefile_false_negatives SKIPPED (Wind...) [ 62%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_dataclass[True] PASSED [ 63%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_dataclass[False] PASSED [ 64%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle[True] PASSED [ 65%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle[False] PASSED [ 67%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle_separate_modules[True] PASSED [ 68%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle_separate_modules[False] PASSED [ 69%]
testing/test_pathlib.py::TestImportLibMode::test_module_name_from_path PASSED [ 70%]
testing/test_pathlib.py::TestImportLibMode::test_resolve_pkg_root_and_module_name PASSED [ 71%]
testing/test_pathlib.py::TestImportLibMode::test_insert_missing_modules PASSED [ 72%]
testing/test_pathlib.py::TestImportLibMode::test_parent_contains_child_module_attribute PASSED [ 73%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_package[True] PASSED [ 74%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_package[False] PASSED [ 75%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_root_is_package PASSED [ 76%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first[True] PASSED [ 77%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first[False] PASSED [ 78%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first_integration[True] PASSED [ 79%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first_integration[False] PASSED [ 80%]
testing/test_pathlib.py::TestImportLibMode::test_import_path_imports_correct_file[True] PASSED [ 81%]
testing/test_pathlib.py::TestImportLibMode::test_import_path_imports_correct_file[False] PASSED [ 82%]
testing/test_pathlib.py::test_safe_exists PASSED                         [ 83%]
testing/test_pathlib.py::test_import_sets_module_as_attribute PASSED     [ 84%]
testing/test_pathlib.py::test_import_sets_module_as_attribute_without_init_files PASSED [ 85%]
testing/test_pathlib.py::test_import_sets_module_as_attribute_regression PASSED [ 86%]
testing/test_pathlib.py::test_import_submodule_not_namespace PASSED      [ 87%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[prepend] PASSED [ 88%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[append] PASSED [ 89%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[importlib] PASSED [ 90%]
testing/test_pathlib.py::TestNamespacePackages::test_ns_multiple_levels_import_rewrite_assertions PASSED [ 91%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[prepend] PASSED [ 92%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[append] PASSED [ 93%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[importlib] PASSED [ 94%]
testing/test_pathlib.py::TestNamespacePackages::test_detect_meta_path PASSED [ 95%]
testing/test_pathlib.py::TestNamespacePackages::test_full_ns_packages_without_init_files[True] PASSED [ 96%]
testing/test_pathlib.py::TestNamespacePackages::test_full_ns_packages_without_init_files[False] PASSED [ 97%]
testing/test_pathlib.py::test_is_importable PASSED                       [ 98%]
testing/test_pathlib.py::test_compute_module_name PASSED                 [100%]

======================== 96 passed, 1 skipped in 1.05s =========================


[2025-02-06 11:11:26] INFO - tester.py: 257

{'total': 97, 'passed': 96, 'xpassed': 0, 'failed': 0, 'xfailed': 0, 'deselected': 0, 'skipped': 1, 'warning': 0, 'error': 0}

[2025-02-06 11:11:26] INFO - tester.py: 436

Number of test evals in current unit test: 97

[2025-02-06 11:11:26] INFO - tester.py: 66

Stopping and removing container 'xuehang_7_pytest_container_cleanup_on_exit_Thu_Feb__6_11_11_20_2025'...

Successfully removed container 'xuehang_7_pytest_container_cleanup_on_exit_Thu_Feb__6_11_11_20_2025'

[2025-02-06 11:11:26] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:27] INFO - exetest.py: 155

Successfully removed target directory at '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/'

[2025-02-06 11:11:27] INFO - tester.py: 79

Removing temporary directory used for repository at '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/'

[2025-02-06 11:11:27] INFO - callee_builder.py: 480

[Execution Test for 'gold_code + new_context'] Passed


[2025-02-06 11:11:27] INFO - callee_builder.py: 297

Preparing docker env for execution test...

[2025-02-06 11:11:27] WARNING - callee_builder.py: 123

Failed to remove file `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c55793b0001492f`: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c55793b0001492f'
Attempting file removal again...

[2025-02-06 11:11:27] WARNING - callee_builder.py: 123

Failed to remove file `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs00000000005e8b360001492e`: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs00000000005e8b360001492e'
Attempting file removal again...

[2025-02-06 11:11:27] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack'
Attempting directory removal again...

[2025-02-06 11:11:27] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects'
Attempting directory removal again...

[2025-02-06 11:11:27] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git'
Attempting directory removal again...

[2025-02-06 11:11:27] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest'
Attempting directory removal again...

[2025-02-06 11:11:27] INFO - callee_builder.py: 134

Successfully removed directory at '/shared/nas2/xuehangg/syncbench_build/code/callee7/'

[2025-02-06 11:11:27] INFO - builder.py: 176

Checking if Docker image 'xuehang/7_pytest' exists...

Docker image 'xuehang/7_pytest' already exists with ID: 2ad0b81aebdc

[2025-02-06 11:11:27] INFO - handler.py: 30

Successfiully created local path: `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-06 11:11:27] INFO - handler.py: 42

Container xuehang_7_pytest_3.11__Thu__Feb____6__11_11_27__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-06 11:11:27] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 324)

[2025-02-06 11:11:28] INFO - exetest.py: 155

Successfully removed target directory at `/shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/`

[2025-02-06 11:11:28] INFO - tester.py: 79

Removing temporary directory used for repository at '/shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/'

[2025-02-06 11:11:28] INFO - caller_builder.py: 486

[Execution Test for 'original_code + new_context'] Passed


[2025-02-06 11:11:28] INFO - caller_builder.py: 695

[2025-02-06 11:11:28] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 316)

[2025-02-06 11:11:28] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 316)

[2025-02-06 11:11:29] INFO - caller_builder.py: 276

Successfully saved data to '/shared/nas2/xuehangg/syncbench_build/dataset/caller_21_mlflow.json


================================================================================================================================================================

                                                        Multi-level Filtering 207/391: [test_oss_utils.py]

================================================================================================================================================================



=========================  Function/method filtering 1/2: [test_oss_utils.py] -> [test_oss_utils.py] -> [test_get_oss_host_creds]  =========================

[2025-02-06 11:11:29] WARNING - caller_builder.py: 388

An error occurred when tracing commit history: /shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow
Attemptaining again...

[2025-02-06 11:11:29] INFO - builder.py: 176

Checking if Docker image 'xuehang/21_mlflow' exists...

Docker image 'xuehang/21_mlflow' already exists with ID: 73f308f5c08c

[2025-02-06 11:11:29] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/`.

Removing existing repo and re-cloning...

[2025-02-06 11:11:29] INFO - exetest.py: 155

Successfully removed target directory at `/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/`

[2025-02-06 11:11:29] INFO - handler.py: 30

Successfiully created local path: `/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/`

[2025-02-06 11:11:29] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/

[2025-02-06 11:11:29] INFO - handler.py: 77

Container xuehang_7_pytest_3.11__Thu__Feb____6__11_11_27__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-06 11:11:29] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-06 11:11:29] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `cleanup_on_exit` in the context_code.

[2025-02-06 11:11:29] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py' already exists.

[2025-02-06 11:11:29] INFO - callee_builder.py: 305

Using docker image with ID: 2ad0b81aebdc

[2025-02-06 11:11:29] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`.

Skipping repo clone...

[2025-02-06 11:11:29] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `cleanup_on_exit` in the context_code.

[2025-02-06 11:11:29] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 312)

[2025-02-06 11:11:29] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py

[2025-02-06 11:11:29] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py'

[2025-02-06 11:11:29] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/testing/test_pathlib.py` in Docker container `xuehang_7_pytest_container_cleanup_on_exit_Thu_Feb__6_11_11_29_2025`...

[2025-02-06 11:11:30] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 312)

[2025-02-06 11:11:30] INFO - handler.py: 42

Container xuehang_21_mlflow_3.11__Thu__Feb____6__11_11_29__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-06 11:11:30] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 312)

[2025-02-06 11:11:31] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 312)

[2025-02-06 11:11:36] WARNING - tracer.py: 84

Skipping commit due to parsing error: invalid syntax (<unknown>, line 312)

[2025-02-06 11:11:36] INFO - tester.py: 92

Execution succeeded!
Container output: 
Obtaining file:///workspace/test_repo
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: iniconfig in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (2.0.0)
Requirement already satisfied: packaging in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (24.1)
Requirement already satisfied: pluggy<2,>=1.5 in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (1.5.0)
Building wheels for collected packages: pytest
  Building editable for pytest (pyproject.toml): started
  Building editable for pytest (pyproject.toml): finished with status 'done'
  Created wheel for pytest: filename=pytest-8.4.0.dev64+g72c682ff9.d20250206-0.editable-py3-none-any.whl size=9450 sha256=328c080395f689f7f7b5b09cb86989019f71a1a86f3b40f6e98f391387dda689
  Stored in directory: /tmp/pip-ephem-wheel-cache-8mwerxej/wheels/77/6d/8d/6d288ec591919a528b58517c67f4d12e0e98d23d266200ee38
Successfully built pytest
Installing collected packages: pytest
  Attempting uninstall: pytest
    Found existing installation: pytest 8.4.0.dev64+g72c682ff9
    Uninstalling pytest-8.4.0.dev64+g72c682ff9:
      Successfully uninstalled pytest-8.4.0.dev64+g72c682ff9
Successfully installed pytest-8.4.0.dev64+g72c682ff9.d20250206
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.4.0.dev64+g72c682ff9.d20250206, pluggy-1.5.0 -- /workspace/test_venv/bin/python
cachedir: .pytest_cache
rootdir: /workspace/test_repo
configfile: pyproject.toml
plugins: asyncio-0.24.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
collecting ... collected 97 items

testing/test_pathlib.py::TestFNMatcherPort::test_matching[*.py-foo.py] PASSED [  1%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[*.py-bar/foo.py] PASSED [  2%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[test_*.py-foo/test_foo.py] PASSED [  3%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/*.py-tests/foo.py] PASSED [  4%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[/c/*.py-/c/foo.py] PASSED [  5%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[/c/foo/*.py-/c/foo/foo.py] PASSED [  6%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/test*.py-tests/foo/test_foo.py] PASSED [  7%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/doc/test*.py-tests/foo/bar/doc/test_foo.py] PASSED [  8%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/doc/**/test*.py-tests/foo/doc/bar/test_foo.py] PASSED [  9%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching_abspath PASSED [ 10%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[*.py-foo.pyc] PASSED [ 11%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[*.py-foo/foo.pyc] PASSED [ 12%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/*.py-foo/foo.py] PASSED [ 13%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[/c/*.py-/d/foo.py] PASSED [ 14%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[/c/foo/*.py-/d/foo/foo.py] PASSED [ 15%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/test*.py-tests/foo.py] PASSED [ 16%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/test*.py-foo/test_foo.py] PASSED [ 17%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/doc/test*.py-tests/foo/bar/doc/foo.py] PASSED [ 18%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/doc/test*.py-tests/foo/bar/test_foo.py] PASSED [ 19%]
testing/test_pathlib.py::TestImportPath::test_smoke_test[True] PASSED    [ 20%]
testing/test_pathlib.py::TestImportPath::test_smoke_test[False] PASSED   [ 21%]
testing/test_pathlib.py::TestImportPath::test_import_path_missing_file[True] PASSED [ 22%]
testing/test_pathlib.py::TestImportPath::test_import_path_missing_file[False] PASSED [ 23%]
testing/test_pathlib.py::TestImportPath::test_renamed_dir_creates_mismatch[True] PASSED [ 24%]
testing/test_pathlib.py::TestImportPath::test_renamed_dir_creates_mismatch[False] PASSED [ 25%]
testing/test_pathlib.py::TestImportPath::test_messy_name[True] PASSED    [ 26%]
testing/test_pathlib.py::TestImportPath::test_messy_name[False] PASSED   [ 27%]
testing/test_pathlib.py::TestImportPath::test_dir[True] PASSED           [ 28%]
testing/test_pathlib.py::TestImportPath::test_dir[False] PASSED          [ 29%]
testing/test_pathlib.py::TestImportPath::test_a[True] PASSED             [ 30%]
testing/test_pathlib.py::TestImportPath::test_a[False] PASSED            [ 31%]
testing/test_pathlib.py::TestImportPath::test_b[True] PASSED             [ 32%]
testing/test_pathlib.py::TestImportPath::test_b[False] PASSED            [ 34%]
testing/test_pathlib.py::TestImportPath::test_c[True] PASSED             [ 35%]
testing/test_pathlib.py::TestImportPath::test_c[False] PASSED            [ 36%]
testing/test_pathlib.py::TestImportPath::test_d[True] PASSED             [ 37%]
testing/test_pathlib.py::TestImportPath::test_d[False] PASSED            [ 38%]
testing/test_pathlib.py::TestImportPath::test_import_after[True] PASSED  [ 39%]
testing/test_pathlib.py::TestImportPath::test_import_after[False] PASSED [ 40%]
testing/test_pathlib.py::TestImportPath::test_check_filepath_consistency[True] PASSED [ 41%]
testing/test_pathlib.py::TestImportPath::test_check_filepath_consistency[False] PASSED [ 42%]
testing/test_pathlib.py::TestImportPath::test_ensuresyspath_append[True] PASSED [ 43%]
testing/test_pathlib.py::TestImportPath::test_ensuresyspath_append[False] PASSED [ 44%]
testing/test_pathlib.py::TestImportPath::test_invalid_path[True] PASSED  [ 45%]
testing/test_pathlib.py::TestImportPath::test_invalid_path[False] PASSED [ 46%]
testing/test_pathlib.py::TestImportPath::test_importmode_importlib[True] PASSED [ 47%]
testing/test_pathlib.py::TestImportPath::test_importmode_importlib[False] PASSED [ 48%]
testing/test_pathlib.py::TestImportPath::test_remembers_previous_imports[True] PASSED [ 49%]
testing/test_pathlib.py::TestImportPath::test_remembers_previous_imports[False] PASSED [ 50%]
testing/test_pathlib.py::TestImportPath::test_no_meta_path_found[True] PASSED [ 51%]
testing/test_pathlib.py::TestImportPath::test_no_meta_path_found[False] PASSED [ 52%]
testing/test_pathlib.py::test_resolve_package_path PASSED                [ 53%]
testing/test_pathlib.py::test_package_unimportable PASSED                [ 54%]
testing/test_pathlib.py::test_access_denied_during_cleanup PASSED        [ 55%]
testing/test_pathlib.py::test_long_path_during_cleanup PASSED            [ 56%]
testing/test_pathlib.py::test_get_extended_length_path_str PASSED        [ 57%]
testing/test_pathlib.py::test_suppress_error_removing_lock PASSED        [ 58%]
testing/test_pathlib.py::test_bestrelpath PASSED                         [ 59%]
testing/test_pathlib.py::test_commonpath PASSED                          [ 60%]
testing/test_pathlib.py::test_visit_ignores_errors PASSED                [ 61%]
testing/test_pathlib.py::test_samefile_false_negatives SKIPPED (Wind...) [ 62%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_dataclass[True] PASSED [ 63%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_dataclass[False] PASSED [ 64%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle[True] PASSED [ 65%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle[False] PASSED [ 67%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle_separate_modules[True] PASSED [ 68%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle_separate_modules[False] PASSED [ 69%]
testing/test_pathlib.py::TestImportLibMode::test_module_name_from_path PASSED [ 70%]
testing/test_pathlib.py::TestImportLibMode::test_resolve_pkg_root_and_module_name PASSED [ 71%]
testing/test_pathlib.py::TestImportLibMode::test_insert_missing_modules PASSED [ 72%]
testing/test_pathlib.py::TestImportLibMode::test_parent_contains_child_module_attribute PASSED [ 73%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_package[True] PASSED [ 74%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_package[False] PASSED [ 75%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_root_is_package PASSED [ 76%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first[True] PASSED [ 77%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first[False] PASSED [ 78%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first_integration[True] PASSED [ 79%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first_integration[False] PASSED [ 80%]
testing/test_pathlib.py::TestImportLibMode::test_import_path_imports_correct_file[True] PASSED [ 81%]
testing/test_pathlib.py::TestImportLibMode::test_import_path_imports_correct_file[False] PASSED [ 82%]
testing/test_pathlib.py::test_safe_exists PASSED                         [ 83%]
testing/test_pathlib.py::test_import_sets_module_as_attribute PASSED     [ 84%]
testing/test_pathlib.py::test_import_sets_module_as_attribute_without_init_files PASSED [ 85%]
testing/test_pathlib.py::test_import_sets_module_as_attribute_regression PASSED [ 86%]
testing/test_pathlib.py::test_import_submodule_not_namespace PASSED      [ 87%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[prepend] PASSED [ 88%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[append] PASSED [ 89%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[importlib] PASSED [ 90%]
testing/test_pathlib.py::TestNamespacePackages::test_ns_multiple_levels_import_rewrite_assertions PASSED [ 91%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[prepend] PASSED [ 92%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[append] PASSED [ 93%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[importlib] PASSED [ 94%]
testing/test_pathlib.py::TestNamespacePackages::test_detect_meta_path PASSED [ 95%]
testing/test_pathlib.py::TestNamespacePackages::test_full_ns_packages_without_init_files[True] PASSED [ 96%]
testing/test_pathlib.py::TestNamespacePackages::test_full_ns_packages_without_init_files[False] PASSED [ 97%]
testing/test_pathlib.py::test_is_importable PASSED                       [ 98%]
testing/test_pathlib.py::test_compute_module_name PASSED                 [100%]

======================== 96 passed, 1 skipped in 0.98s =========================


[2025-02-06 11:11:36] INFO - tester.py: 257

{'total': 97, 'passed': 96, 'xpassed': 0, 'failed': 0, 'xfailed': 0, 'deselected': 0, 'skipped': 1, 'warning': 0, 'error': 0}

[2025-02-06 11:11:36] INFO - tester.py: 436

Number of test evals in current unit test: 97

[2025-02-06 11:11:36] INFO - tester.py: 66

Stopping and removing container 'xuehang_7_pytest_container_cleanup_on_exit_Thu_Feb__6_11_11_29_2025'...

Successfully removed container 'xuehang_7_pytest_container_cleanup_on_exit_Thu_Feb__6_11_11_29_2025'
